apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hviy5qhzt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hviy5qhzt-java-quarkus-gitops